### ISSUE TITLE
Start using Gitflow in every repo

### ISSUE THREAD

**Issue by fidel-ml** [gobstones/.github#7]
Although we wrote we are using Gitflow, we are still not doing it... As we are going to invite new members, it is a good momento to start...
 - [ ] .github
 - [ ] gobstones-admin-dashboard
 - [ ] gobstones-assertions
 - [ ] gobstones-blocks
 - [ ] gobstones-blocks-react
 - [ ] gobstones-board
 - [ ] gobstones-board-react
 - [ ] gobstones-code-editor
 - [ ] gobstones-core
 - [ ] gobstones-ide
 - [ ] gobstones-gbb-parser
 - [ ] gobstones-guidelines (issue#2)
 - [ ] gobstones-lang
 - [ ] gobstones-lang-intl
 - [ ] gobstones-lint
 - [ ] gobstones-markdown-view
 - [ ] gobstones-parser
 - [ ] gobstones-refactors
 - [ ] gobstones-scripts (issue#1)
 - [ ] gobstones-server
 - [ ] gobstones-test
 - [ ] gobstones-typechecker
 - [ ] gobstones-api-docs
 - [ ] template-gobstones-typescript-library

**Comment by fidel-ml** [comment]
We will use GitHub Flow instead. So, no develop branches are needed.
